### ISSUE TITLE
I have a question?

### ISSUE THREAD

**Issue by Blizzard-liu** [80945540/FreeBook#3]
每次请求网络时,第一次总是失败,重新尝试才能加载,这是为何?

**Comment by 80945540** [comment]
你的这个问题我会留意 因为有缓存 我在调试的时候没注意  有空我会搞定这个问题  你要是有兴趣 可以尝试的去看看  我代码写的很清晰的

**Comment by Blizzard-liu** [comment]
我还是菜鸟一个,借你的app学习呢

**Comment by 80945540** [comment]
哦哦  好的  尝试下嘛  遇到什么不懂得  找我呀   我现在  在写API接口 抓包什么的还是不放到app内部  http://123.56.221.114/help.html
